### ISSUE TITLE
fix pymdown-extensions syntax

### ISSUE THREAD

**Issue by JessicaS11** [jpsca/jinja-markdown#2]
Hello! I was working to install jinja-markdown after a manual install of dependencies and noticed that in `setup.cfg` your [install requires list](https://github.com/jpsca/jinja-markdown/blob/c96891722202aa1c88e4e6717ee2fa1de7e44ad3/setup.cfg#L19) has `pymdown_extensions` instead of `pymdown-extensions` (underscore instead of dash). Naturally, conda couldn't find the former.

**Comment by jpsca** [comment]
Good catch, thanks.
